import type { ApiCampaignNote, ApiCharacter, ApiEpisode, ApiFaction, ApiJob, ApiNpc, CampaignMembership, CampaignNote, CampaignRecord, Character, CharacterDraft, EpisodeRecord, FactionRecord, Mission, NpcRecord } from "@/lib/campaign/types";

export function getAttachedArtUrl(signedUrl: string | null | undefined, path: string | null | undefined): string | null { return signedUrl ?? (path?.startsWith("http") ? path : null); }
export function mapApiJob(job: ApiJob, index: number): Mission { return { id: job.id, title: job.title, category: job.status === "open" ? "OPEN JOB" : `${job.status.toUpperCase()} SIGNAL`, summary: job.summary || "No public mission brief recorded.", giver: job.giver.name, giverType: job.giver.type, votes: job.votes, accent: (["cyan", "pink", "amber"] as const)[index % 3], image: getAttachedArtUrl(job.art_url, job.art_path), voted: job.voted, status: job.status, playerNotesMarkdown: job.player_notes_markdown, giverId: job.giver_npc_id ?? job.giver_faction_id ?? "", placeId: job.place_id, artPath: job.art_path, artUrl: job.art_url ?? null, artPrompt: job.art_prompt, artProvider: job.art_provider, artSubject: job.art_subject, hook: job.hook, gmNotesMarkdown: job.gm_notes_markdown }; }
export function mapApiCharacter(character: ApiCharacter, index: number): Character { const colors = ["pink", "cyan", "purple", "amber"] as const; return { id: character.id, ownerId: character.owner_id, name: character.name, species: character.species, className: character.class_name, level: character.level, subtitle: [character.species, character.class_name].filter(Boolean).join(" ") || "Unclassified crew member", detail: `${character.class_name || "Unassigned class"} // Level ${character.level}`, color: colors[index % colors.length], image: getAttachedArtUrl(character.art_url, character.art_path), status: "ACTIVE", backstoryMarkdown: character.backstory_markdown, physicalDescription: character.physical_description, artPath: character.art_path, artUrl: character.art_url ?? null, artSubject: character.art_subject, artPrompt: character.art_prompt, artProvider: character.art_provider ?? null, canEdit: character.can_edit ?? false }; }
export function mapApiNpc(npc: ApiNpc, index: number): NpcRecord { return { ...npc, color: (["cyan", "amber", "pink"] as const)[index % 3] }; }
export function mapApiFaction(faction: ApiFaction, index: number): FactionRecord { return { ...faction, color: (["pink", "cyan", "amber"] as const)[index % 3] }; }
export function mapApiNote(note: ApiCampaignNote, index: number): CampaignNote { return { ...note, accent: (["cyan", "pink", "amber", "purple"] as const)[index % 4] }; }
export function mapApiEpisode(episode: ApiEpisode, index: number): EpisodeRecord { return { ...episode, accent: (["cyan", "pink", "amber"] as const)[index % 3] }; }
export function getCampaignRecord(membership: CampaignMembership): CampaignRecord | null { return (Array.isArray(membership.campaign) ? membership.campaign[0] : membership.campaign) ?? null; }
export function toCharacterDraft(character: Character): CharacterDraft { return { name: character.name, species: character.species, className: character.className, level: character.level, backstoryMarkdown: character.backstoryMarkdown, physicalDescription: character.physicalDescription, artSubject: character.artSubject ?? "", artPath: character.artPath ?? null, artUrl: character.artUrl ?? null, artPrompt: character.artPrompt ?? null, artProvider: character.artProvider ?? null }; }