import { Shield, Swords, WandSparkles } from "lucide-react";
import type { ReactNode } from "react";
import type { EnemyStatBlockV1 } from "@/lib/validation/enemy";

function StatLine({ label, children }: { label: string; children: ReactNode }) {
  return <div className="grid grid-cols-[minmax(88px,.32fr)_minmax(0,1fr)] gap-3 border-b border-[rgba(139,151,169,.12)] py-[7px] last:border-b-0"><strong className="text-[var(--dim)] font-mono text-[8px] tracking-[.08em]">{label}</strong><span className="text-[var(--muted)] text-[10px] leading-[1.5] [overflow-wrap:anywhere]">{children}</span></div>;
}

function ListText({ values, empty = "None recorded" }: { values: string[]; empty?: string }) {
  return values.length ? values.join(", ") : empty;
}

export default function EnemyStatBlock({ statBlock }: { statBlock: EnemyStatBlockV1 | null | undefined }) {
  if (!statBlock) return <p className="m-0 text-[var(--dim)] text-[10px]">No structured mechanics are available.</p>;
  return <section data-enemy-stat-block="true" className="grid gap-[14px] border border-[rgba(255,92,154,.25)] bg-[rgba(255,92,154,.035)] p-[14px]">
    <div className="flex items-center gap-2 border-b border-[rgba(255,92,154,.18)] pb-[10px]"><Swords size={15} className="text-[var(--pink)]" /><p className="m-0 text-[var(--pink)] font-mono text-[9px] tracking-[.13em]">STRUCTURED STAT BLOCK{" // "}GM ONLY</p></div>
    {statBlock.recallKnowledge ? <div><p className="m-0 mb-1 text-[var(--pink)] font-mono text-[8px] tracking-[.1em]">RECALL KNOWLEDGE</p><StatLine label="DC">{statBlock.recallKnowledge.dc} {statBlock.recallKnowledge.entries.length ? `// ${statBlock.recallKnowledge.entries.map((entry) => `${entry.trait} (${entry.skill})`).join(", ")}` : ""}{statBlock.recallKnowledge.adjustmentNote ? ` // ${statBlock.recallKnowledge.adjustmentNote}` : ""}</StatLine></div> : null}
    <div className="grid gap-1">
      <StatLine label="PERCEPTION">{statBlock.perception.modifier >= 0 ? "+" : ""}{statBlock.perception.modifier}{statBlock.perception.senses.length ? ` // ${statBlock.perception.senses.map((sense) => `${sense.name}${sense.range ? ` ${sense.range}` : ""}${sense.notes ? ` (${sense.notes})` : ""}`).join(", ")}` : ""}{statBlock.perception.notes ? ` // ${statBlock.perception.notes}` : ""}</StatLine>
      <StatLine label="LANGUAGES"><ListText values={statBlock.languages.names} />{statBlock.languages.additionalCount ? ` // +${statBlock.languages.additionalCount} additional` : ""}{statBlock.languages.communicationNotes ? ` // ${statBlock.languages.communicationNotes}` : ""}</StatLine>
      <StatLine label="SKILLS"><ListText values={statBlock.skills.map((skill) => `${skill.name} ${skill.modifier >= 0 ? "+" : ""}${skill.modifier}${skill.notes ? ` (${skill.notes})` : ""}`)} /></StatLine>
      <StatLine label="ABILITIES">{Object.entries(statBlock.abilityModifiers).map(([key, value]) => `${key.slice(0, 3).toUpperCase()} ${value >= 0 ? "+" : ""}${value}`).join(" // ")}</StatLine>
      <StatLine label="ITEMS"><ListText values={statBlock.items} /></StatLine>
    </div>
    <div className="grid gap-1">
      <div className="flex items-center gap-2 pb-[3px]"><Shield size={14} className="text-[var(--pink)]" /><p className="m-0 text-[var(--pink)] font-mono text-[8px] tracking-[.1em]">DEFENSES</p></div>
      <StatLine label="AC">{statBlock.defenses.armorClass}{statBlock.defenses.armorClassNotes ? ` // ${statBlock.defenses.armorClassNotes}` : ""}</StatLine>
      <StatLine label="SAVES">Fort {statBlock.defenses.saves.fortitude.modifier >= 0 ? "+" : ""}{statBlock.defenses.saves.fortitude.modifier}{statBlock.defenses.saves.fortitude.notes ? ` (${statBlock.defenses.saves.fortitude.notes})` : ""}{" // "}Ref {statBlock.defenses.saves.reflex.modifier >= 0 ? "+" : ""}{statBlock.defenses.saves.reflex.modifier}{statBlock.defenses.saves.reflex.notes ? ` (${statBlock.defenses.saves.reflex.notes})` : ""}{" // "}Will {statBlock.defenses.saves.will.modifier >= 0 ? "+" : ""}{statBlock.defenses.saves.will.modifier}{statBlock.defenses.saves.will.notes ? ` (${statBlock.defenses.saves.will.notes})` : ""}</StatLine>
      <StatLine label="HP"><ListText values={statBlock.defenses.hitPoints.map((entry) => `${entry.label} ${entry.value}${entry.notes ? ` (${entry.notes})` : ""}`)} /></StatLine>
      <StatLine label="IMMUNITIES"><ListText values={statBlock.defenses.immunities} /></StatLine>
      <StatLine label="RESISTANCES"><ListText values={statBlock.defenses.resistances} /></StatLine>
      <StatLine label="WEAKNESSES"><ListText values={statBlock.defenses.weaknesses} /></StatLine>
      {statBlock.defenses.notes ? <StatLine label="DEFENSE NOTES">{statBlock.defenses.notes}</StatLine> : null}
    </div>
    <StatLine label="MOVEMENT"><ListText values={statBlock.movement.map((movement) => `${movement.mode} ${movement.speed}${movement.notes ? ` (${movement.notes})` : ""}`)} /></StatLine>
    {statBlock.strikes.length ? <div className="grid gap-1"><div className="flex items-center gap-2 pb-[3px]"><Swords size={14} className="text-[var(--pink)]" /><p className="m-0 text-[var(--pink)] font-mono text-[8px] tracking-[.1em]">STRIKES</p></div>{statBlock.strikes.map((strike, index) => <div className="border border-[rgba(139,151,169,.12)] p-[9px]" key={`${strike.category}-${strike.name}-${index}`}><strong className="text-[var(--ink)] text-[10px]">{strike.category.toUpperCase()} {strike.name}</strong><p className="m-0 mt-1 text-[var(--muted)] text-[10px]">Attack {strike.attackModifier >= 0 ? "+" : ""}{strike.attackModifier}{strike.multipleAttackPenalty.length ? ` // MAP ${strike.multipleAttackPenalty.map((modifier) => `${modifier >= 0 ? "+" : ""}${modifier}`).join("/")}` : ""}{strike.activation ? ` // ${strike.activation}` : ""}{strike.reach ? ` // Reach ${strike.reach}` : ""}{strike.range ? ` // Range ${strike.range}` : ""}{strike.traits.length ? ` // ${strike.traits.join(", ")}` : ""}{" // "}Damage {strike.damage.map((damage) => `${damage.formula} ${damage.type}${damage.notes ? ` (${damage.notes})` : ""}`).join(", ") || "not recorded"}</p>{strike.rider ? <p className="m-0 mt-1 text-[var(--muted)] text-[10px] leading-[1.5]">{strike.rider}</p> : null}{strike.rawText ? <p className="m-0 mt-1 text-[var(--dim)] text-[9px] leading-[1.5]">{strike.rawText}</p> : null}</div>)}</div> : null}
    {statBlock.spellcasting.length ? <div className="grid gap-1"><div className="flex items-center gap-2 pb-[3px]"><WandSparkles size={14} className="text-[var(--pink)]" /><p className="m-0 text-[var(--pink)] font-mono text-[8px] tracking-[.1em]">SPELLCASTING</p></div>{statBlock.spellcasting.map((casting, index) => <div className="border border-[rgba(139,151,169,.12)] p-[9px]" key={`${casting.tradition}-${index}`}><strong className="text-[var(--ink)] text-[10px]">{casting.tradition.toUpperCase()} {casting.method.toUpperCase()}{casting.dc !== null ? ` // DC ${casting.dc}` : ""}{casting.attackModifier !== null ? ` // Attack ${casting.attackModifier >= 0 ? "+" : ""}${casting.attackModifier}` : ""}</strong>{casting.entries.map((entry, entryIndex) => <p className="m-0 mt-1 text-[var(--muted)] text-[10px]" key={`${entry.rank}-${entryIndex}`}>{entry.rank}: {entry.spells.join(", ") || "none recorded"}{entry.uses ? ` // ${entry.uses}` : ""}{entry.frequency ? ` // ${entry.frequency}` : ""}{entry.notes ? ` // ${entry.notes}` : ""}</p>)}{casting.notes ? <p className="m-0 mt-1 text-[var(--dim)] text-[9px]">{casting.notes}</p> : null}</div>)}</div> : null}
    {statBlock.specialAbilities.length ? <div className="grid gap-1"><p className="m-0 text-[var(--pink)] font-mono text-[8px] tracking-[.1em]">SPECIAL ABILITIES</p>{statBlock.specialAbilities.map((ability, index) => <div className="border border-[rgba(139,151,169,.12)] p-[9px]" key={`${ability.section}-${ability.name}-${index}`}><strong className="text-[var(--ink)] text-[10px]">{ability.name}</strong><span className="ml-2 text-[var(--pink)] font-mono text-[8px]">{ability.activation}{ability.actionCost ? ` // ${ability.actionCost}` : ""}{ability.traits.length ? ` // ${ability.traits.join(", ")}` : ""}</span><p className="m-0 mt-1 text-[var(--muted)] text-[10px] leading-[1.5]">{ability.effect}</p>{[ability.frequency, ability.trigger, ability.requirements, ability.area, ability.save, ability.cooldown].filter(Boolean).map((detail, detailIndex) => <p className="m-0 mt-1 text-[var(--dim)] text-[9px]" key={`${ability.name}-detail-${detailIndex}`}>{detail}</p>)}{ability.rawText && ability.rawText !== ability.effect ? <p className="m-0 mt-1 text-[var(--dim)] text-[9px] leading-[1.5]">{ability.rawText}</p> : null}</div>)}</div> : null}
    {statBlock.unparsedFragments.length ? <div className="border border-dashed border-[rgba(245,184,75,.35)] p-[9px] text-[var(--amber)] text-[9px]">{statBlock.unparsedFragments.map((fragment, index) => <p className="m-0" key={`${fragment.label}-${index}`}>{fragment.label}: {fragment.text} ({fragment.reason})</p>)}</div> : null}
  </section>;
}
